"""Add article lists

Revision ID: 105fc26a8c47
Revises: 9da63d42cc45
Create Date: 2024-05-10 22:42:29.179634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision: str = '105fc26a8c47'
down_revision: Union[str, None] = '9da63d42cc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_list',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'list_id')
    )

    # Add a default list for favorited articles
    timestamp_now = datetime.datetime.now().isoformat()
    op.execute(
        f"""
            INSERT INTO list
            (id, name, description, order_number, created_at, updated_at)
            VALUES
            (0, 'Bookmarks', 'Bookmarked Articles', -10, '{timestamp_now}', '{timestamp_now}')
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_list')
    op.drop_table('list')
    # ### end Alembic commands ###
