"""Add default category

Revision ID: 9da63d42cc45
Revises: ec3d06a248de
Create Date: 2024-05-07 22:53:36.049732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da63d42cc45'
down_revision: Union[str, None] = 'ec3d06a248de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a row in category that is a default category
    op.execute("INSERT INTO category (id, name, description, order_number) VALUES (0, 'Default', 'Default Category', -10)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete the default category
    op.execute("DELETE FROM category WHERE name = 'default'")
    # ### end Alembic commands ###
