"""Add order to category

Revision ID: ec3d06a248de
Revises: 084a90479515
Create Date: 2024-05-07 17:53:01.403541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3d06a248de'
down_revision: Union[str, None] = '084a90479515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('order_number', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Sqlite3 doesn't support dropping columns, you need to use alter table drop
    # op.drop_column('category', 'order_number')
    op.execute('ALTER TABLE category DROP COLUMN order_number')
    # ### end Alembic commands ###
